// Bundles the Markdown guides into src/GuideContent.gs so the Apps Script "Publish Guides to Google Docs"
// menu can push them into the guild's existing Google Docs. Run automatically by `npm run gas:push`.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// Repo path -> title shown in the sheet when asking for / confirming each Doc
const GUIDES = [
  ['OFFICER_GUIDE.md', 'Officer & Raid Leader Guide'],
  ['RAIDER_GUIDE.md', 'Raider Guide'],
  ['README.md', 'Project README'],
  ['discord-bot/README.md', 'Discord Bot Setup']
];

function buildGuideContentSource() {
  const entries = GUIDES.map(([file, title]) => {
    const markdown = fs.readFileSync(path.join(ROOT, file), 'utf8').replace(/\r\n/g, '\n');
    return `  ${JSON.stringify(file)}: {\n    title: ${JSON.stringify(title)},\n    markdown: ${JSON.stringify(markdown)}\n  }`;
  });
  return '// AUTO-GENERATED by scripts/build-guides.js from the Markdown guides in the repo. Do not edit by hand;\n' +
    '// edit the .md files and run `npm run build:guides` (gas:push does this automatically).\n' +
    'const GUIDE_CONTENT = {\n' + entries.join(',\n') + '\n};\n';
}

if (require.main === module) {
  fs.writeFileSync(path.join(ROOT, 'src', 'GuideContent.gs'), buildGuideContentSource());
  console.log(`Bundled ${GUIDES.length} guides into src/GuideContent.gs`);
}

module.exports = { buildGuideContentSource, GUIDES };
